---
- name: Install required packages
  include_role:
    name: vm
    tasks_from: install_suse_package
  vars:
    suse_packages: [python310, python310-pip, python310-devel, gcc, python310-dbm]

- name: Select python althernative
  become: yes
  community.general.alternatives:
    name: python
    path: /usr/bin/python3.10
    priority: 1
    link: /usr/bin/python
